on:
  push:
    branches:
    - release
  workflow_dispatch:

jobs:
  job_build:
    name: Build on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]

    steps:
